=== maybuzani/liga-mx-xml-/resultados.dtd
<!ELEMENT liga (jornada+)>
        <!ELEMENT jornada (partido+)>

        <!ELEMENT partido (local, visitante, estadio?)>

        <!ELEMENT local (nombre, goles, estadisticas?)>
        <!ELEMENT visitante (nombre, goles, estadisticas?)>

        <!ELEMENT nombre (#PCDATA)>
        <!ELEMENT goles (#PCDATA)>
        <!ELEMENT estadio (#PCDATA)>

        <!ELEMENT estadisticas (falta | tiro | tarjeta)*>
        <!ELEMENT falta (#PCDATA)>
        <!ELEMENT tiro (#PCDATA)>
        <!ELEMENT tarjeta (#PCDATA)>

=== maybuzani/liga-mx-xml-/resultados.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE liga SYSTEM "../dtd/resultados.dtd">
<liga>
    <jornada>
        <partido id="P101">
            <local>
                <nombre>Toluca</nombre>
                <goles>2</goles>
                <estadisticas>
                    <tiro>12</tiro>
                    <falta>8</falta>
                    <tarjeta>Amarilla a Baeza</tarjeta>
                </estadisticas>
            </local>
            <visitante>
                <nombre>Pachuca</nombre>
                <goles>1</goles>
                <estadisticas>
                    <tiro>9</tiro>
                    <falta>14</falta>
                    <tarjeta>Roja a Cabral</tarjeta>
                </estadisticas>
            </visitante>
            <estadio>Nemesio Diez</estadio>
        </partido>

        <partido id="P102">
            <local>
                <nombre>Santos Laguna</nombre>
                <goles>0</goles>
                <estadisticas>
                    <tiro>7</tiro>
                    <falta>11</falta>
                </estadisticas>
            </local>
            <visitante>
                <nombre>Pumas UNAM</nombre>
                <goles>1</goles>
                <estadisticas>
                    <tiro>10</tiro>
                    <falta>9</falta>
                    <tarjeta>Amarilla a Huerta</tarjeta>
                </estadisticas>
            </visitante>
            <estadio>Corona</estadio>
        </partido>

        <partido id="P103">
            <local>
                <nombre>Monterrey</nombre>
                <goles>3</goles>
                <estadisticas>
                    <tiro>15</tiro>
                    <falta>10</falta>
                    <tarjeta>Amarilla a Canales</tarjeta>
                </estadisticas>
            </local>
            <visitante>
                <nombre>Club Leon</nombre>
                <goles>1</goles>
                <estadisticas>
                    <tiro>6</tiro>
                    <falta>13</falta>
                </estadisticas>
            </visitante>
            <estadio>BBVA</estadio>
        </partido>
    </jornada>
</liga>

=== maybuzani/liga-mx-xml-/resultados-invalido.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE liga SYSTEM "../dtd/resultados.dtd">
<liga>
    <jornada>
        <partido id="P101">
            <local>
                <nombre>America</nombre>
                <goles>2</goles>
            </local>
        </partido>

        <partido id="P102">
            <local>
                <nombre>America</nombre>
                <goles>2</goles>
            </local>
            <local>
                <nombre>Guadalajara</nombre>
                <goles>1</goles>
            </local>
            <visitante>
                <nombre>Pumas</nombre>
                <goles>0</goles>
            </visitante>
        </partido>

        <partido id="P103">
            <estadio>Estadio Azteca</estadio>
            <local>
                <nombre>America</nombre>
                <goles>2</goles>
            </local>
            <visitante>
                <nombre>Guadalajara</nombre>
                <goles>1</goles>
            </visitante>
        </partido>

        <partido>
            <local>
                <nombre>Cruz Azul</nombre>
                <goles>1</goles>
            </local>
            <visitante>
                <nombre>Atlas</nombre>
                <goles>0</goles>
            </visitante>
        </partido>

        <partido id="P101">
            <local>
                <nombre>Tigres</nombre>
                <goles>3</goles>
            </local>
            <visitante>
                <nombre>Rayados</nombre>
                <goles>2</goles>
            </visitante>
        </partido>

        <partido id="P104">
            <arbitro>Marco Ortiz</arbitro>
            <local>
                <nombre>Puebla</nombre>
                <goles>0</goles>
            </local>
            <visitante>
                <nombre>Toluca</nombre>
                <goles>1</goles>
            </visitante>
        </partido>
    </jornada>
</liga>
